name: Truffle Unittests

on:
  push:
    branches:
    - master

  pull_request:
    branches:
      - "*"
jobs:
  run_truffle_unittests:
    runs-on: ubuntu-latest
    name: Run the Truffle unit tests
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run ganache &
    - run: npm run test

